// <auto-generated />
namespace wn_Admin.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class int2double : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(int2double));
        
        string IMigrationMetadata.Id
        {
            get { return "201510012109091_int2double"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
