// <auto-generated />
namespace wn_Admin.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class keystates : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(keystates));
        
        string IMigrationMetadata.Id
        {
            get { return "201507131645282_keystates"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
