// <auto-generated />
namespace wn_Admin.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class TimeOff : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(TimeOff));
        
        string IMigrationMetadata.Id
        {
            get { return "201507021542022_TimeOff"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
