// <auto-generated />
namespace wn_Admin.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class off_status : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(off_status));
        
        string IMigrationMetadata.Id
        {
            get { return "201509301957018_off_status"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
