// <auto-generated />
namespace wn_Admin.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class fk_ws : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(fk_ws));
        
        string IMigrationMetadata.Id
        {
            get { return "201509301554252_fk_ws"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
